# Generated by Django 4.2.10 on 2024-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccReceiptFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('tax_type_id', models.SmallIntegerField()),
                ('receipt_flag', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_receipt_flags',
            },
        ),
        migrations.CreateModel(
            name='AppClientSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('client_address', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('muntax_url', models.CharField(max_length=255)),
                ('munacc_url', models.CharField(max_length=255)),
                ('current_fiscal_year_code', models.CharField(max_length=255)),
                ('current_fiscal_year_id', models.SmallIntegerField()),
                ('receipt_type', models.CharField(max_length=255)),
                ('receipt_value', models.CharField(max_length=255)),
                ('current_year_rate_id', models.CharField(max_length=255)),
                ('previous_year_rate_id', models.CharField(max_length=255)),
                ('current_year_rate_value', models.SmallIntegerField()),
                ('previous_year_rate_value', models.SmallIntegerField()),
                ('land_measuring_id', models.SmallIntegerField()),
                ('land_measuring_unit', models.SmallIntegerField()),
                ('land_measuring_unit_name', models.CharField(max_length=255)),
                ('length_id', models.SmallIntegerField()),
                ('length_unit', models.SmallIntegerField()),
                ('length_unit_name', models.CharField(max_length=255)),
                ('last_fiscal_year', models.CharField(max_length=255)),
                ('client_username', models.CharField(max_length=255)),
                ('tax_amount_from', models.CharField(max_length=255)),
                ('tax_amount_to', models.CharField(max_length=255)),
                ('is_house_land_tax_implemented', models.BooleanField(default=False)),
                ('is_ward_wise_psp_mode', models.BooleanField(default=False)),
                ('is_ebps', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_client_settings',
            },
        ),
        migrations.CreateModel(
            name='MstPaymentWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('code', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('is_web_payment', models.BooleanField(default=False)),
                ('is_token_payment', models.BooleanField(default=False)),
                ('is_ebps', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_payment_wallets',
            },
        ),
        migrations.CreateModel(
            name='MstTaxTypeOnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('tax_type_id', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_tax_type_online_payment',
            },
        ),
        migrations.CreateModel(
            name='MstThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('code', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_third_party',
            },
        ),
        migrations.CreateModel(
            name='MstUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SmallIntegerField()),
                ('code', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_np', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_user_types',
            },
        ),
    ]
