from django.db import models


# Create your models here.
class WebPaymentLogModel(models.Model):
    client_id = models.SmallIntegerField(null=False)
    payment_ward = models.SmallIntegerField()
    taxpayer_new_iid = models.SmallIntegerField()
    calc_id = models.IntegerField()
    tax_type_id = models.SmallIntegerField()
    evaluation_date_bs = models.CharField(max_length=255)
    tax_payable = models.IntegerField()
    eservice_trans_ref_code = models.CharField(max_length=255)
    psp_code = models.CharField(max_length=255)
    psp_trans_ref_code = models.CharField(max_length=255)
    psp_reference_token = models.CharField(max_length=255)
    psp_payment_status = models.BooleanField(default=False)
    psp_payment_message = models.CharField(max_length=255)
    psp_generated_token = models.CharField(max_length=255)
    fonepay_data_validation = models.CharField(max_length=500)
    fonepay_product_number = models.CharField(max_length=255)
    fonepay_remarks1 = models.CharField(max_length=255)
    fonepay_remarks2 = models.CharField(max_length=255)
    fonepay_qr_message = models.CharField(max_length=500)
    fonepay_deviceId = models.CharField(max_length=255)
    fonepay_merchant_websocket_url = models.CharField(max_length=255)
    fonepay_third_party_websocket_url = models.CharField(max_length=255)
    fonepay_client_code = models.CharField(max_length=255)
    fonepay_requested_date = models.CharField(max_length=255)
    fonepay_third_party_qr_url = models.CharField(max_length=255)
    psp_verification_status = models.BooleanField(default=False)
    psp_verification_datetime = models.DateTimeField(auto_now_add=True)
    psp_verification_message = models.CharField(max_length=255)
    munerp_receipt_id = models.SmallIntegerField()
    munerp_receipt_number = models.CharField(max_length=255)
    munerp_update_status = models.BooleanField(default=False)
    munerp_update_message = models.CharField(max_length=255)
    munerp_update_datetime = models.DateTimeField(auto_now_add=True)
    pdf_generate_status = models.BooleanField(default=False)
    pdf_generate_datetime = models.DateTimeField(auto_now_add=True)
    pdf_generate_message = models.CharField(max_length=255)
    pdf_file_path = models.CharField(max_length=255)
    reprocess_date = models.DateTimeField(auto_now_add=True)
    is_reprocess = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'web_payment_logs'
